import os, random

menuStr = "Password Generator\n1) Open\n2) Passwords\n3) Close"
windowStr = "Enter the number of characters of your strong password."

history = []


menu = True
window = True




def passwordGenerator(number_input):
    number_of_characters = number_input
    characters = [random.randint(32,126) for i in range(number_of_characters)] # A random number for accessing the ASCII table is assigned to characters with a range that is the range of the input.
    password = [chr(i) for i in characters] # The password is then generated by accessing the ASCII table for characters
    string = ""
    for i in range(len(password)):
        string = string + password[i] + " "
    return string

def is_convertible_to_int(s):
    try:
        a = int(s)
        return True
    except ValueError:
        return False

while menu:

	os.system("cls")

	print(menuStr)

	choice = input("Choose option --> ")

	if is_convertible_to_int(choice) and (choice == "1" or choice == "2" or choice == "3"):

		choice = int(choice)

		if choice == 1:
			window = True
		elif choice == 2:

			os.system("cls")
			for i in range(len(history)):
				print(history[i])
			input("Go Back")
			window = False


		elif choice == 3:
			window = False
			menu = False

		while window:

			os.system("cls")

			print(windowStr)

			characters = input("----->  ")

			if is_convertible_to_int(characters):
				characters = int(characters)

				password = passwordGenerator(characters)
				history.append(password)

				print("Show password?")

				userPasswordChoice = input("(Yes) --- (No) ----> ")

				if userPasswordChoice == "Yes" or userPasswordChoice == "yes":
					print(password)
					print("Password is saved in Passwords.")
					
					

				elif userPasswordChoice == "No" or userPasswordChoice == "no":
					print("Password is saved in Passwords.")

				else:
					print("Invalid Input")
					input("Go Back")
					





				input("Go Back ")
				break


			else:
				print("Invalid Selection")
				input("Go Back")

			break

	else:
		print("Invalid Selection")
		input("Go Back")
